version: 2.0
jobs:

  setup-build-deploy:
    docker:
      - image: python:3.7-buster
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: "26:bd:89:63:be:7d:ce:a2:99:7f:99:e6:e1:19:f8:f3"
      - restore_cache:
          key: dst-doc-{{ arch }}-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: apt-get update
      - run: bash setup.sh --quiet-mode
      - save_cache:
          key: dst-doc-{{ arch }}-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run: make html
      - run: git config --global user.name "circle-ci"
      - run: git config --global user.email "circle-ci@nomail.com"
      - run: make stage
      - run: make deploy


workflows:
  version: 2
  build-deploy-docs:
    jobs:
      - setup-build-deploy
